GhostHuntAR/GhostHuntAR.Web/Controllers/ImageController.cs
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GhostHuntAR.Infrastructure.Abstract;
using GhostHuntAR.Infrastructure.Helpers;
using GhostHuntAR.Infrastructure.Models.TransmitModels;
using log4net;
using VikingErik.Mvc.ResumingActionResults;

namespace GhostHuntAR.Web.Controllers
{
  public class ImageController : Controller
  {

    private static readonly ILog Log = LogHelper.GetLogger
        (typeof(ImageController));

    private IImageService db;

    public ImageController(IImageService _is)
    {
      db = _is;
    }

    //
    // GET: /Image/

    public FileResult Index(long id)
    {
      try
      {
        return db.Get(id);
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return null;
      }
    }

    [HttpPost]
    [Authorize]
    public ActionResult Create(long ghLocationId, HttpPostedFileBase[] images, string[] imageCaptions)
    {
      try
      {
        for (var i = 0; i < images.Length; i++)
        {
          if (!string.IsNullOrEmpty(imageCaptions[i]))
            db.Save(ghLocationId, images[i], imageCaptions[i], UserHelper.Instance.CurrentUserName);
          else
            return null;
        }

        //if (Request.UrlReferrer != null && Request.UrlReferrer.AbsoluteUri != null)
        //return new RedirectResult(Request.UrlReferrer.AbsoluteUri);
        //else
        return RedirectToAction("All", "Manage");
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return HttpNotFound();
      }
    }

    [Authorize]
    public ActionResult Edit(long id)
    {
      try
      {
        if (Request.UrlReferrer != null)
          ViewBag.ReferrerUrl = Request.UrlReferrer.AbsoluteUri;

        var i = db.GetImage(id);

        if (i.UserName != UserHelper.Instance.CurrentUserName)
          return HttpNotFound();

        return View(i);
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return HttpNotFound();
      }
    }

    [HttpPost]
    [Authorize]
    public ActionResult Edit(long id, string imageCaption, string referrerUrl)
    {
      try
      {
        var oldImage = db.GetImage(id);

        if (oldImage.UserName != UserHelper.Instance.CurrentUserName)
          return new HttpStatusCodeResult(405, "unauthorized image edit");

        db.Dispose();

        db.Update(id, null, imageCaption);

        if (referrerUrl == "AJAX")
          return new JsonResult() { Data = new { Status = "OK" } };
        if (!string.IsNullOrEmpty(referrerUrl))
          return new RedirectResult(referrerUrl);


        return RedirectToAction("Index", "Manage");
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return HttpNotFound();
      }
    }

    [HttpPost]
    [Authorize]
    public ActionResult Delete(long id)
    {
      try
      {
        var image = db.GetImage(id);
        if (image.UserName != UserHelper.Instance.CurrentUserName)
          return new HttpStatusCodeResult(405, "unauthorized image delete");

        db.Delete(id);

        if (Request.UrlReferrer != null && Request.UrlReferrer.AbsoluteUri != null)
          return new RedirectResult(Request.UrlReferrer.AbsoluteUri);
        else
          return RedirectToAction("Index", "Manage");
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return HttpNotFound();
      }
    }

    [ChildActionOnly]
    public ActionResult ListByUser()
    {
      try
      {
        var sounds = db.FindAllByUserName(UserHelper.Instance.CurrentUserName);

        return PartialView(sounds);
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return HttpNotFound();
      }
    }

    [ChildActionOnly]
    public ActionResult ListByLocation(long id)
    {
      try
      {
        var sounds = db.FindAllByGHLocationID(id);

        return PartialView(sounds);
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return HttpNotFound();
      }
    }

    public ResumingFileStreamResult ThumbNail(long id)
    {
      try
      {
        var i = db.GetImage(id);
        var contentType = db.GetContentType(id);

        var ms = new MemoryStream(i.Thumbnail);
        return new ResumingFileStreamResult(ms, contentType);
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return null;
      }
    }

    [HttpPost]
    public JsonResult GetPagedImagesByUserName(string id, int page, int pageSize)
    {
      try
      {
        var images = db.FindAllByUserName(id, page, pageSize).ToList();
        var itms = images.Select(i => new ImageTransmitModel(i)).ToList();

        var jr = new JsonResult();
        jr.MaxJsonLength = int.MaxValue;
        jr.Data = itms;

        return jr;
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return null;
      }
    }

    [HttpPost]
    public JsonResult GetPagedImagesByGHLocationId(int id, int page, int pageSize)
    {
      try
      {
        var images = db.FindAllByGHLocationID(id, page, pageSize).ToList();
        var itms = images.Select(i => new ImageTransmitModel(i)).ToList();

        var jr = new JsonResult();
        jr.MaxJsonLength = int.MaxValue;
        jr.Data = itms;

        return jr;
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return null;
      }
    }
  }
}

GhostHuntAR/GhostHuntAR.Web/Controllers/SearchController.cs
using System;
using System.Web.Mvc;
using GhostHuntAR.Infrastructure.Abstract;
using GhostHuntAR.Infrastructure.Helpers;
using GhostHuntAR.Infrastructure.Models.TransmitModels;
using log4net;

namespace GhostHuntAR.Web.Controllers
{
  [AllowAnonymous]
  public class SearchController : Controller
  {

    private static readonly ILog Log = LogHelper.GetLogger
        (typeof(SearchController));

    private IGHLocationRepository _lr;
    private readonly ISearchService _ss;

    public SearchController(IGHLocationRepository lr, ISearchService ss)
    {
      _lr = lr;
      _ss = ss;
    }

    //
    // GET: /Search/

    public ActionResult Form()
    {
      return View();
    }

    public JsonResult Index(string address, string latitude, string longitude, string keywords, string distanceType, string radius)
    {
      try
      {
        var locations = _ss.Search(address, latitude, longitude, keywords, distanceType,
                                   radius, UserHelper.Instance.CurrentUserId);

        if (locations == null)
          return new JsonResult() { Data = null };

        var ghLocations = locations.Select(l => new GHLocationListItemTransmitModel(l));

        var jr = new JsonResult();
        jr.MaxJsonLength = int.MaxValue;
        jr.Data = ghLocations;

        return jr;
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return null;
      }
    }

    public ActionResult Results(string address, string city, string state, string zip, string latitude, string longitude, string keywords, string distanceType, string radius)
    {
      try
      {
        var locations = _ss.Search(address, city, state, zip, latitude, longitude, keywords, distanceType,
                                   radius, UserHelper.Instance.CurrentUserId);

        return View(locations);
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return HttpNotFound();
      }
    }

  }
}

GhostHuntAR/GhostHuntAR.Web/Controllers/SoundController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GhostHuntAR.Infrastructure.Abstract;
using GhostHuntAR.Infrastructure.Helpers;
using log4net;
using VikingErik.Mvc.ResumingActionResults;

namespace GhostHuntAR.Web.Controllers
{
  public class SoundController : Controller
  {

    private static readonly ILog Log = LogHelper.GetLogger
        (typeof(SoundController));

    private ISoundService db;

    public SoundController(ISoundService ss)
    {
      db = ss;
    }

    //
    // GET: /Sound/

    public ResumingFileStreamResult Index(long id)
    {
      try
      {
        return db.Get(id);
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return null;
      }
    }

    [HttpPost]
    [Authorize]
    public ActionResult Create(long ghLocationId, HttpPostedFileBase[] sounds, string[] soundDescriptions)
    {
      try
      {
        for (var i = 0; i < sounds.Length; i++)
        {
          if (!string.IsNullOrEmpty(soundDescriptions[i]))
            db.Save(ghLocationId, sounds[i], soundDescriptions[i], UserHelper.Instance.CurrentUserName);
          else
            return null;
        }

        //if (Request.UrlReferrer != null && Request.UrlReferrer.AbsoluteUri != null)
        //return new RedirectResult(Request.UrlReferrer.AbsoluteUri);
        //else
        return RedirectToAction("All", "Manage");
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return HttpNotFound();
      }
    }

    [Authorize]
    public ActionResult Edit(long id)
    {
      try
      {
        var s = db.GetSound(id);

        if (s.UserName != UserHelper.Instance.CurrentUserName)
          return HttpNotFound();

        if (Request.UrlReferrer != null)
          ViewBag.ReferrerUrl = Request.UrlReferrer.AbsoluteUri;

        return View(s);
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return HttpNotFound();
      }
    }

    [HttpPost]
    [Authorize]
    public ActionResult Edit(long id, string soundDescription, string referrerUrl)
    {
      try
      {
        var oldSound = db.GetSound(id);

        if (oldSound.UserName != UserHelper.Instance.CurrentUserName)
          return new HttpStatusCodeResult(405, "Unauthorized sound edit");

        db.Dispose();

        db.Update(id, null, soundDescription);

        if (referrerUrl == "AJAX")
          return new JsonResult() { Data = new { Status = "OK" } };
        if (!string.IsNullOrEmpty(referrerUrl))
          return new RedirectResult(referrerUrl);

        return RedirectToAction("Index", "Manage");
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return HttpNotFound();
      }
    }

    [HttpPost]
    [Authorize]
    public ActionResult Delete(long id)
    {
      try
      {
        var sound = db.GetSound(id);
        if (sound.UserName != UserHelper.Instance.CurrentUserName)
          return new HttpStatusCodeResult(405, "Unauthorized sound delete");

        db.Delete(id);

        if (Request.UrlReferrer != null && Request.UrlReferrer.AbsoluteUri != null)
          return new RedirectResult(Request.UrlReferrer.AbsoluteUri);
        else
          return RedirectToAction("Index", "Manage");
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return HttpNotFound();
      }
    }

    [ChildActionOnly]
    public ActionResult ListByUser()
    {
      try
      {
        var sounds = db.FindAllByUserName(UserHelper.Instance.CurrentUserName);

        return PartialView(sounds);
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return HttpNotFound();
      }
    }

    [ChildActionOnly]
    public ActionResult ListByLocation(long id)
    {
      try
      {
        var sounds = db.FindAllByGHLocationID(id);

        return PartialView(sounds);
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return HttpNotFound();
      }
    }

    [HttpPost]
    public JsonResult GetPagedSoundsByUserName(string id, int page, int pageSize)
    {
      try
      {
        var jr = new JsonResult();
        jr.Data = db.FindAllByUserName(id, page, pageSize).ToList();

        return jr;
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return null;
      }
    }

    [HttpPost]
    public JsonResult GetPagedSoundsByGHLocationId(int id, int page, int pageSize)
    {
      try
      {
        var jr = new JsonResult();
        jr.Data = db.FindAllByGHLocationID(id, page, pageSize).ToList();

        return jr;
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return null;
      }
    }

  }

}

GhostHuntAR/GhostHuntAR.Web/Controllers/TextController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using GhostHuntAR.Infrastructure.Abstract;
using GhostHuntAR.Infrastructure.Helpers;
using GhostHuntAR.Infrastructure.Models;
using log4net;

namespace GhostHuntAR.Web.Controllers
{
  public class TextController : Controller
  {

    private static readonly ILog Log = LogHelper.GetLogger
        (typeof(TextController));

    private ITextService db;

    public TextController(ITextService ts)
    {
      db = ts;
    }

    //
    // GET: /Image/

    public string Index(long id)
    {
      try
      {
        return db.Get(id);
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return null;
      }
    }

    [HttpPost]
    [Authorize]
    public ActionResult Create(long ghLocationId, string title, string textBody)
    {
      try
      {
        db.Save(ghLocationId, title, textBody, UserHelper.Instance.CurrentUserName);

        if (Request.UrlReferrer != null && Request.UrlReferrer.AbsoluteUri != null)
          return new RedirectResult(Request.UrlReferrer.AbsoluteUri);
        else
          return RedirectToAction("Index", "Manage");
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return HttpNotFound();
      }
    }

    [Authorize]
    public ActionResult Edit(long id)
    {
      try
      {
        var ft = new FullText();
        ft.Text = db.GetText(id);
        ft.RawText = db.Get(id);

        if (ft.Text.UserName != UserHelper.Instance.CurrentUserName)
          return HttpNotFound();

        return View(ft);
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return HttpNotFound();
      }
    }

    [HttpPost]
    [Authorize]
    public ActionResult Edit(long id, string title, string textBody = null, string referrerUrl = null)
    {
      try
      {
        var oldText = db.GetText(id);

        if (oldText.UserName != UserHelper.Instance.CurrentUserName)
          return new HttpStatusCodeResult(405, "Unauthorized text edit");

        db.Dispose();

        if (!string.IsNullOrEmpty(textBody))
          db.Update(id, title, textBody);
        else
          db.Update(id, title);

        if (!string.IsNullOrEmpty(referrerUrl) && referrerUrl == "AJAX")
          return new JsonResult() { Data = new { Status = "OK" } };
        if (Request.UrlReferrer != null && Request.UrlReferrer.AbsoluteUri != null)
          return new RedirectResult(Request.UrlReferrer.AbsoluteUri);
        else
          return RedirectToAction("Index", "Manage");
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return HttpNotFound();
      }
    }

    [HttpPost]
    [Authorize]
    public ActionResult Delete(long id)
    {
      try
      {
        var oldText = db.GetText(id);

        if (oldText.UserName != UserHelper.Instance.CurrentUserName)
          return new HttpStatusCodeResult(405, "Unauthorized text delete");

        db.Delete(id);

        if (Request.UrlReferrer != null && Request.UrlReferrer.AbsoluteUri != null)
          return new RedirectResult(Request.UrlReferrer.AbsoluteUri);
        else
          return RedirectToAction("Index", "Manage");
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return HttpNotFound();
      }
    }

    [ChildActionOnly]
    public ActionResult ListByUser()
    {
      try
      {
        var sounds = db.FindAllByUserName(UserHelper.Instance.CurrentUserName);

        return PartialView(sounds);
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return HttpNotFound();
      }
    }

    [ChildActionOnly]
    public ActionResult ListByLocation(long id)
    {
      try
      {
        var sounds = db.FindAllByGHLocationID(id);

        return PartialView(sounds);
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return HttpNotFound();
      }
    }

    public ActionResult Display(long id)
    {
      try
      {
        var ft = new FullText();
        ft.Text = db.GetText(id);
        ft.RawText = db.Get(id);
        return View(ft);
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return HttpNotFound();
      }
    }

    [HttpPost]
    public JsonResult GetPagedTextsByUserName(string id, int page, int pageSize)
    {
      try
      {
        var jr = new JsonResult();
        jr.Data = db.FindAllByUserName(id, page, pageSize).ToList();

        return jr;
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return null;
      }
    }

    [HttpPost]
    public JsonResult GetPagedTextsByGHLocationId(int id, int page, int pageSize)
    {
      try
      {
        var jr = new JsonResult();
        jr.Data = db.FindAllByGHLocationID(id, page, pageSize).ToList();

        return jr;
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return null;
      }
    }
  }
}

GhostHuntAR/GhostHuntAR.Web/Views/Home/DisplayAdminOptions.cshtml
@{
  ViewBag.Title = "Admin Options";
}

<h2>Display Admin Options</h2>

GhostHuntAR/GhostHuntAR.Web/Views/Home/Index.cshtml
@using GhostHuntAR.Infrastructure.Helpers
@model GhostHuntAR.Infrastructure.Models.LoginModel

@{
  ViewBag.Title = "";
}

@section styles
{
  @Styles.Render("~/Content/home")
}

<noscript>
  You must have javascript enabled to view this site.
</noscript>

@*<div id="subcontent" class="centered">
      <a href="@Url.Action("Index", "Home")">
          <img style="height: 75px; width: 300px; margin-left: -50px;" class="logo" alt="logo" src="~/Content/shared_images/logo.png"/>
      </a>
  </div>*@

<div id="content" class="centered">

  @if (UserHelper.Instance.IsAuthenticated)
  {
    Html.RenderAction("UserDashboard", "Home", new {id = ViewBag.Id});
  }
  else
  {
    <h4 class="gh-home-index-description">
      Ghost HuntAR is a database of haunted locations through the US.
      Users have the ability to upload images, sounds, videos and text accounts of their experiences at these locations,
      and they can share them with every other user of Ghost HuntAR.
    </h4>

    <br />
    <hr />
    <div class="main-content-color login-height default-set-height">
      <div class="gh-home-index-login-partial-container">
        @{Html.RenderPartial("LoginPartial", Model);}
      </div>
    </div>
  }

</div>

GhostHuntAR/GhostHuntAR.Web/Views/Home/UserDashboard.cshtml
@using GhostHuntAR.Infrastructure.Helpers
@using GhostHuntAR.Infrastructure.Models.Enums
@model IEnumerable<GhostHuntAR.Infrastructure.Models.TransmitModels.GHLocationListItemTransmitModel>

@Styles.Render("~/Content/home")

<script type="text/javascript">
  window.locationObjs = {};
  window.locationTitles = {};
  window.currentUserId = '@UserHelper.Instance.CurrentUserId';
</script>

<div id="content">
  <div class="home-userdashboard-controls" id="controlsAccordion">
    <h3>Locations</h3>
    <div>
      <div class="home-userdashboard-controls-container">
        <select id="locationType" name="locationType">
          <option value="MyEdits">My Edited Locations</option>
          <option value="MyLocations">My Owned Locations</option>
          <option value="SavedSearch">My Last Search</option>
        </select>
        <input value="Submit" type="button" id="locationsTypeSubmitButton" />
        <br />
        <p> - OR - </p>
        <span>Enter Keywords: </span>
        <input title="Keywords" id="keywords" name="keywords" type="text" />
        <span> Or Enter Address: </span>
        <input title="Address" id="address" name="address" type="text" />
        <select title="Distance Units" id="distanceType" name="distanceType">
          @foreach (var distanceType in Enum.GetValues(typeof (DistanceTypes)).Cast<DistanceTypes>())
          {
            <option>@distanceType.ToString()</option>
          }
        </select>
        <select title="Radius" id="radius" name="radius">
          <option>5</option>
          <option>10</option>
          <option>15</option>
          <option>20</option>
          <option>25</option>
          <option>30</option>
          <option>35</option>
          <option>40</option>
          <option>45</option>
          <option>50</option>
          <option>55</option>
          <option>60</option>
          <option>65</option>
          <option>70</option>
          <option>75</option>
          <option>80</option>
          <option>85</option>
          <option>90</option>
          <option>95</option>
          <option>100</option>
        </select>
        <input id="searchSubmitButton" type="button" value="Submit" />
      </div>
    </div>
  </div>
  <div id="dashboardContent">

    <div class="dashboard-left">
      <div class="dashboard-left-header">
        <h2></h2>
        <a href="#"></a>
      </div>

      <div class="dashboard-left-top">

      </div>

      <div class="dashboard-left-bottom">
        <ul id="locationList">
          @foreach (var l in Model)
          {
            <script type="text/javascript">
              window.locationTitles[parseInt('@l.GHLocationID')] = '@l.Title';
            </script>
            <li>
              <div class="ghlocation-list-item">
                <input type="hidden" value="@l.GHLocationID" />
                <h3 id='ghLocation_@l.GHLocationID' class="ghlocation-list-item-activate">@l.Title</h3>
                <div class="icon-container">
                  @if (l.CreatedByUserID == UserHelper.Instance.CurrentUserId)
                  {
                    <a title="Edit" href='@Url.Action("Edit", "Manage", new {id = l.GHLocationID})'><img alt="Edit" src="~/Content/shared_images/editicon.png" /></a>
                    <span>|</span>
                  }
                  <a title="Add Sounds/Images/Texts/Videos" href='@Url.Action("AddSightsAndSounds", "Manage", new {id = l.GHLocationID})'><img alt="Add" src="~/Content/shared_images/addicon.png" /></a>
                </div>
              </div>
            </li>
          }
          @*@for (var i = 0; i < 100; i++)
            {
              <li>
                <div class="ghlocation-list-item">
                  <h3>Test</h3>
                  <div class="icon-container">
                    <a href='@Url.Action("Display", "Manage", new { id = 1 })'><img src="~/Content/shared_images/editicon.png" /></a>
                  </div>
              </div>
              </li>
            }*@
        </ul>
      </div>

    </div>

    <div class="dashboard-right">
      <div id="userInfoDiv">
        <span style="float: left;">Welcome, @Html.ActionLink(UserHelper.Instance.CurrentUser.Name ?? UserHelper.Instance.CurrentUserName, "Index", "Account", new {id = UserHelper.Instance.CurrentUserName}, new {target = "_blank", title = UserHelper.Instance.CurrentUserName})!</span>
        <br />
        <div class="user-controls-div">
          @Html.ActionLink("Manage Settings", "Manage", "Account", new {}, new {target = "_blank", @class = "user-navigation-a"})
          @using (Html.BeginForm("LogOff", "Account"))
          {
            @Html.AntiForgeryToken()
            <input class="user-info-button" type="submit" value="Log Off" />
          }
          @Html.ActionLink("New Location", "Create", "Manage", new { }, new { target = "_blank", @class = "user-navigation-a border-left-black" })
        </div>
      </div>
      <div style="display: none;" id="userDashboardTabs">
        <ul>
          <li><a href="#soundContainer">Sound</a></li>
          <li><a href="#videoContainer">Video</a></li>
          <li><a href="#imageContainer">Image</a></li>
          <li><a href="#textContainer">Text</a></li>
        </ul>

        <div class="dashboard-tab" style="padding-left: 30px; text-align: left;" id="soundContainer">

        </div>

        <div class="dashboard-tab" style="padding-left: 30px; text-align: left;" id="videoContainer">

        </div>

        <div class="dashboard-tab" style="padding-left: 30px; text-align: left;" id="imageContainer">

        </div>

        <div class="dashboard-tab" style="padding-left: 30px; text-align: left;" id="textContainer">

        </div>

      </div>
    </div>
  </div>
  
  <div style="display: none;" id="editDialog">
  </div>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryui")
@Scripts.Render("~/bundles/home")

<script type="text/javascript">

  ////////////////////////////////////////////////////////////////////////////////////////

  var sasa = new SightsAndSoundsAjax({
    urls: {
      user: {
        sound: '@Url.Action("GetPagedSoundsByUserName", "Sound", new {id = string.Empty})',
        image: '@Url.Action("GetPagedImagesByUserName", "Image", new {id = string.Empty})',
        text: '@Url.Action("GetPagedTextsByUserName", "Text", new {id = string.Empty})',
        video: '@Url.Action("GetPagedVideosByUserName", "Video", new {id = string.Empty})'
      },

      location: {
        sound: '@Url.Action("GetPagedSoundsByGHLocationId", "Sound", new {id = string.Empty})',
        image: '@Url.Action("GetPagedImagesByGHLocationId", "Image", new {id = string.Empty})',
        text: '@Url.Action("GetPagedTextsByGHLocationId", "Text", new {id = string.Empty})',
        video: '@Url.Action("GetPagedVideosByGHLocationId", "Video", new {id = string.Empty})'
      }

    },

    containerIds: {
      sound: "#soundContainer",
      image: "#imageContainer",
      text: "#textContainer",
      video: "#videoContainer"
    },

    pageSizes: {
      sound: '@ViewBag.soundPageSize',
      image: '@ViewBag.imagePageSize',
      text: '@ViewBag.textPageSize',
      video: '@ViewBag.videoPageSize'
    },

    viewUrls: {
      sound: '@Url.Action("Index", "Sound", new {id = string.Empty})',
      image: '@Url.Action("Index", "Image", new {id = string.Empty})',
      text: '@Url.Action("Index", "Text", new {id = string.Empty})',
      video: '@Url.Action("Display", "Video", new {id = string.Empty})'
    },

    editUrls: {
      sound: '@Url.Action("Edit", "Sound", new {id = string.Empty})',
      image: '@Url.Action("Edit", "Image", new {id = string.Empty})',
      text: '@Url.Action("Edit", "Text", new {id = string.Empty})',
      video: '@Url.Action("Edit", "Video", new {id = string.Empty})'
    },

    deleteUrls: {
      sound: '@Url.Action("Delete", "Sound", new {id = string.Empty})',
      image: '@Url.Action("Delete", "Image", new {id = string.Empty})',
      text: '@Url.Action("Delete", "Text", new {id = string.Empty})',
      video: '@Url.Action("Delete", "Video", new {id = string.Empty})'
    },

    userNameUrl: '@Url.Action("Index", "Account", new {id = string.Empty})',

    thumbNailUrl: '@Url.Action("ThumbNail", "Image", new {id = string.Empty})',

    locationTitleUrl: '@Url.Action("GetLocationTitle", "Manage", new {id = string.Empty})',

    currentUserName: '@UserHelper.Instance.CurrentUserName'

  });

  var ud = new UserDashboard({
    editLocationUrl: '@Url.Action("Edit", "Manage", new {id = string.Empty})',
    addSightsAndSoundsUrl: '@Url.Action("AddSightsAndSounds", "Manage", new {id = string.Empty})',
    locationImageUrl: '@Url.Action("Image", "Manage", new {id = string.Empty})',
    indexLocationUrl: '@Url.Action("Index", "Manage", new {id = string.Empty})',
    indexSearchUrl: '@Url.Action("Index", "Search", new {id = string.Empty})',
    indexHomeUrl: '@Url.Action("Index", "Home", new {id = string.Empty})',
    sasa: sasa
  });

  Home(ud, sasa);

  ////////////////////////////////////////////////////////////////////////////////////////

</script>