GhostHuntAR/GhostHuntAR.Web/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Http;
using GhostHuntAR.Infrastructure.Abstract;
using GhostHuntAR.Infrastructure.Models.TransmitModels;
using GhostHuntAR.Web.Filters;
using log4net;
using Supermortal.Common.NonPCL.Helpers;
using Supermortal.Common.NonPCL.Helpers.Log;
using Supermortal.Common.PCL.Helpers;
using Supermortal.Common.PCL.Models;

namespace GhostHuntAR.Web.Controllers
{
  [TokenFilter]
  public class LocationController : ApiController
  {

    private static readonly ILog Log = LogHelper.GetLogger
        (typeof(LocationController));

    private readonly IGHLocationRepository db = (IGHLocationRepository)IoCHelper.Instance.GetService(typeof(IGHLocationRepository));
    private readonly ISessionService _ss = (ISessionService) IoCHelper.Instance.GetService(typeof (ISessionService));

    // GET api/location
    [HttpGet]
    public ServerReturnModel<IEnumerable<GHLocationStatusTransmitModel>> GetLocationIds(double latitude, double longitude, double maxDistanceKilometers, int maxLocations)
    {
      try
      {
        return new ServerReturnModel<IEnumerable<GHLocationStatusTransmitModel>>("OK", db.GetAllLocationIdsWithinDistance(latitude, longitude, maxDistanceKilometers, maxLocations));
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return new ServerReturnModel<IEnumerable<GHLocationStatusTransmitModel>>("ERROR", ex.Message);
      }
    }

    // GET api/location/5
    [HttpGet]
    public ServerReturnModel<GHLocationTransmitModel> GetLocation(long id)
    {
      try
      {
        return new ServerReturnModel<GHLocationTransmitModel>("OK", CacheHelper<GHLocationTransmitModel>.Instance.GetCacheable(id.ToString()));
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return new ServerReturnModel<GHLocationTransmitModel>("ERROR", ex.Message);
      }
    }

    //// POST api/location
    //[HttpPost]
    //public void PostLocation([FromBody]GHLocation location)
    //{
    //  try
    //  {
    //    db.Insert(location);
    //  }
    //  catch (Exception ex)
    //  {
    //    Log.Error(ex.Message, ex);
    //  }
    //}

    //// PUT api/location/5
    //[HttpPost]
    //public void PutLocation([FromBody]GHLocation location)
    //{
    //  try
    //  {
    //    db.Update(location);
    //  }
    //  catch (Exception ex)
    //  {
    //    Log.Error(ex.Message, ex);
    //  }
    //}

    [HttpPost]
    public ServerReturnModel<IEnumerable<GHLocationListItemAPITransmitModel>> GetUserOwnedEditedLocations()
    {
      try
      {
        var token = Request.Headers.SingleOrDefault(h => h.Key == "GH-AUTH-TOKEN").Value.FirstOrDefault();
        var user = _ss.GetUser(token);
        return new ServerReturnModel<IEnumerable<GHLocationListItemAPITransmitModel>>("OK", db.GetAllUserEditedLocationsAPI((user.UserName)).ToList());
      }
      catch (Exception ex)
      {
        return new ServerReturnModel<IEnumerable<GHLocationListItemAPITransmitModel>>("ERROR", ex.Message);
      }
    }

    [HttpPost]
    public ServerReturnModel<IEnumerable<GHLocationListItemAPITransmitModel>> GetUserOwnedLocations()
    {
      try
      {
        var token = Request.Headers.SingleOrDefault(h => h.Key == "GH-AUTH-TOKEN").Value.FirstOrDefault();
        var user = _ss.GetUser(token);
        return new ServerReturnModel<IEnumerable<GHLocationListItemAPITransmitModel>>("OK", db.GetAllUserOwnedLocationsAPI(user.UserId).ToList());
      }
      catch (Exception ex)
      {
        return new ServerReturnModel<IEnumerable<GHLocationListItemAPITransmitModel>>("ERROR", ex.Message);
      }
    }

    [HttpPost]
    public ServerReturnModel<object> GetLocationImage(long id)
    {
      try
      {
        var image = Convert.ToBase64String(db.GetImage(id));
        return new ServerReturnModel<object>("OK", (object)image);
      }
      catch (Exception ex)
      {
        return new ServerReturnModel<object>("ERROR", ex.Message);
      }
    } 
 
    // DELETE api/location/5
    //[HttpPost]
    //public void DeleteLocation(int id)
    //{
    //  try
    //  {
    //    db.Delete(id);
    //  }
    //  catch (Exception ex)
    //  {
    //    Log.Error(ex.Message, ex);
    //  }
    //}

  }
}

GhostHuntAR/GhostHuntAR.Web/Controllers/RemoteSessionController.cs
using System;
using System.Web.Mvc;
using GhostHuntAR.Infrastructure.Abstract;
using GhostHuntAR.Infrastructure.Helpers;
using log4net;

namespace GhostHuntAR.Web.Controllers
{
    [AllowAnonymous]
    public class RemoteSessionController : Controller
    {
        //
        // GET: /RemoteSession/

        private static readonly ILog Log = LogHelper.GetLogger
            (typeof(RemoteSessionController));

        private ISessionService _ss;

        public RemoteSessionController(ISessionService ss)
        {
            _ss = ss;
        }

        [HttpPost]
        public JsonResult LogIn(string userName, string password)
        {
           try
           {
               if (UserHelper.Instance.Login(userName, password, true))
               {

                   var session = _ss.CreateSession(userName);

                   var jr = new JsonResult {Data = new { Status = "Success", Token = session.Token }};
                   return jr;
               }
               else
               {
                   var jr = new JsonResult {Data = new {Status = "Failure"}};
                   return jr;
               }
           }
           catch (Exception ex)
           {
               Log.Error(ex.Message, ex);
               var jr = new JsonResult { Data = new {Status = "Error", Message = ex.Message } };
               return jr;
           }
        }

        [HttpPost]
        public JsonResult Test(string token)
        {
            var valid = _ss.ValidateToken(token);
            var user = _ss.GetUser(token);

            var jr = new JsonResult { Data = new { Status = "Success" } };
            return jr;
        }

    }
}

GhostHuntAR/GhostHuntAR.Web/Controllers/SightsAndSoundsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Http;
using GhostHuntAR.Infrastructure.Abstract;
using GhostHuntAR.Infrastructure.Models;
using GhostHuntAR.Web.Filters;
using log4net;
using Supermortal.Common.NonPCL.Helpers.Log;
using Supermortal.Common.PCL.Helpers;
using Supermortal.Common.PCL.Models;

namespace GhostHuntAR.Web.Controllers
{
  [TokenFilter]
  public class SightsAndSoundsController : ApiController
  {

    private static readonly ILog Log = LogHelper.GetLogger
      (typeof(SightsAndSoundsController));

    private readonly ISoundService _ss = (ISoundService) IoCHelper.Instance.GetService(typeof(ISoundService));
    private readonly IImageService _is = (IImageService) IoCHelper.Instance.GetService(typeof(IImageService));
    private readonly ITextService _ts = (ITextService) IoCHelper.Instance.GetService(typeof(ITextService));
    private readonly IVideoService _vs = (IVideoService) IoCHelper.Instance.GetService(typeof(IVideoService));

    [HttpGet]
    public ServerReturnModel<IEnumerable<Sound>> GetPagedSoundsByGHLocationId(int id, int page, int pageSize)
    {
      try
      {
        return new ServerReturnModel<IEnumerable<Sound>>("OK", _ss.FindAllByGHLocationID(id, page, pageSize).ToArray());
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return new ServerReturnModel<IEnumerable<Sound>>("ERROR", ex.Message);
      }
    }

    //[AllowAnonymous]
    //[HttpGet]
    //public ResumingFileStreamResult GetRawSound(long id)
    //{
    //  try
    //  {
    //    return _ss.Get(id);
    //  }
    //  catch (Exception ex)
    //  {
    //    Log.Error(ex.Message, ex);
    //    return null;
    //  }
    //}

    [HttpGet]
    public ServerReturnModel<IEnumerable<Image>> GetPagedImagesByGHLocationId(int id, int page, int pageSize)
    {
      try
      {
        return new ServerReturnModel<IEnumerable<Image>>("SUCCESS", _is.FindAllByGHLocationID(id, page, pageSize).ToList());
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return new ServerReturnModel<IEnumerable<Image>>("ERROR", ex.Message);
      }
    }

    [HttpGet]
    public ServerReturnModel<object> GetRawImage(long id)
    {
      try
      {
        return new ServerReturnModel<object>("SUCCESS", (object)Convert.ToBase64String(_is.GetBytes(id)));
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return new ServerReturnModel<object>("ERROR", ex.Message);
      }
    }

    [HttpGet]
    public ServerReturnModel<IEnumerable<Text>> GetPagedTextsByGHLocationId(int id, int page, int pageSize)
    {
      try
      {
        return new ServerReturnModel<IEnumerable<Text>>("SUCCESS", _ts.FindAllByGHLocationID(id, page, pageSize).ToList());
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return new ServerReturnModel<IEnumerable<Text>>("ERROR", ex.Message);
      }
    }

    [HttpGet]
    public ServerReturnModel<object> GetRawText(long id)
    {
      try
      {
        return new ServerReturnModel<object>("SUCCESS", (object)_ts.Get(id));
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return new ServerReturnModel<object>("ERROR", ex.Message);
      }
    }

    [HttpGet]
    public ServerReturnModel<IEnumerable<Video>> GetPagedVideosByGHLocationId(int id, int page, int pageSize)
    {
      try
      {
        return new ServerReturnModel<IEnumerable<Video>>("SUCCESS", _vs.FindAllByGHLocationID(id, page, pageSize).ToList());
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return new ServerReturnModel<IEnumerable<Video>>("ERROR", ex.Message);
      }
    }

    [HttpGet]
    public ServerReturnModel<object> GetRawVideo(long id)
    {
      try
      {
        return new ServerReturnModel<object>("SUCCESS", (object)_vs.Get(id));
      }
      catch (Exception ex)
      {
        Log.Error(ex.Message, ex);
        return new ServerReturnModel<object>("ERROR", ex.Message);
      }
    }

  }
}

GhostHuntAR/GhostHuntAR.Web/Views/CacheTest/CacheSizeTest.cshtml
@{
    ViewBag.Title = "Cache Size Test";
}

<h2>Cache Size Test</h2>

GhostHuntAR/GhostHuntAR.Web/Views/CacheTest/HashedQueueTests.cshtml
@{
    ViewBag.Title = "Hashed Queue Tests";
}

<h2>Hashed Queue Tests</h2>

GhostHuntAR/GhostHuntAR.Web/Views/CacheTest/ImageTests.cshtml
@{
    ViewBag.Title = "Image Tests";
}

<h2>Image Tests</h2>

GhostHuntAR/GhostHuntAR.Web/Views/CacheTest/LoadTest.cshtml
@{
  ViewBag.Title = "Load Test";
}

@Styles.Render("~/Content/account")

<div id="content" class="user-page-content main-background-color default-set-height" style="width: 66%;">
  <h2>Load Test</h2>
  
  <input type="button" id="startCacheHelperButton" value="Start Cache Helper" />
  <br />
  <input type="button" id="startLoadTestButton" value="Start Load Test" />
  <br />
  <input type="button" id="killLoadTestButton" value="Kill Load Test" />

  <div id="dataDiv">

  </div>
</div>

@section scripts {
  <script type="text/javascript">

  var CacheLoadTest = {};
  CacheLoadTest.timer = null;

  CacheLoadTest.call = function (id) {

    var postData = {
      id: id
    };

    $.ajax({
      url: '@Url.Action("LoadTestCall")',
      type: 'POST',
      headers: { 'Content-type': 'application/json' },
      dataType: 'json',
      data: JSON.stringify(postData),
      context: document.body,
      success: function (data) {
        //alert(data.Status);
        if (data.Status == "OK") {
          //alert(data.Value.Title);
          //$("#dataDiv").append($("<p>" + data.Value.Title + "</p>"));
        }
      },
      error: function (e) {
        console.log(e);
      }
    });

  }

  $(document).ready(function () {

    $("#startLoadTestButton").click(function () {

      CacheLoadTest.call(1);

      CacheLoadTest.timer = setInterval(function () {

        var index = ((Math.random() * 100) % 4) + 2;
        CacheLoadTest.call(index);

      }, 1000);

    });

    $("#killLoadTestButton").click(function () {

      clearInterval(CacheLoadTest.timer);

      $.ajax({
        url: '@Url.Action("KillLoadTest")',
          type: 'POST',
          headers: { 'Content-type': 'application/json' },
          dataType: 'json',
          //data: JSON.stringify(postData),
          context: document.body,
          success: function (data) {
            //alert(data.Status);
            if (data.Status == "OK") {
              //alert(data.Value.Title);
              //$("#dataDiv").append($("<p>" + data.Value.Title + "</p>"));
            }
          },
          error: function (e) {
            console.log(e);
          }
        });

      });

    $("#startCacheHelperButton").click(function () {

        clearInterval(CacheLoadTest.timer);

        $.ajax({
          url: '@Url.Action("StartCacheHelper")',
          type: 'POST',
          headers: { 'Content-type': 'application/json' },
          dataType: 'json',
          //data: JSON.stringify(postData),
          context: document.body,
          success: function (data) {
            //alert(data.Status);
            if (data.Status == "OK") {
              //alert(data.Value.Title);
              //$("#dataDiv").append($("<p>" + data.Value.Title + "</p>"));
            }
          },
          error: function (e) {
            console.log(e);
          }
        });

      });

    });

  </script>
}

GhostHuntAR/GhostHuntAR.Web/Views/CacheTest/RestTest.cshtml
@{
  ViewBag.Title = "Rest Test";
}

@Styles.Render("~/Content/account")

<div id="content" class="user-page-content main-background-color default-set-height" style="width: 66%;">
  <h2>Rest Test</h2>

  <input data-bind="click: getLocations_click" type="button" value="Get Locations" />
  <br />
  <input data-bind="click: bombard" type="button" value="Bombard" />
  <br />
  <br />
  <p><b>Token: </b></p>
  <p data-bind="text: token"></p>
  <br />
  <table class="centered" data-bind="foreach: locations">
    <tr>
      <td data-bind="text: Title"></td>
    </tr>
  </table>
</div>

@section scripts {

  @Scripts.Render("~/bundles/knockout")

  <script type="text/javascript">

  //"9d7e8737564e64994d57aff1820f9c0e23041ebc54f983b949b7be5a348c18f6"
  function RestTest() {

    this.token = ko.observable(null);
    this.locationIds = ko.observableArray([]);
    this.locations = ko.observableArray([]);

    this.constructor = function () {

      var self = this;

      this.login("admin", "9d7e8737564e64994d57aff1820f9c0e23041ebc54f983b949b7be5a348c18f6", self.sightsAndSoundsTest, { id: 1 });

    };

    this.call = function (url, method, postData, token) {

      var data = null;
      if (postData != null) {
        if (method == "GET") {
          data = postData;
        }
        else {
          data = JSON.stringify(postData);
        }
      }

      return $.ajax({
        url: url,
        type: method,
        headers: { 'Content-type': 'application/json', 'GH-AUTH-TOKEN': token },
        dataType: 'json',
        data: data,
        context: document.body
        //success: function (data) {
        //  //alert(data.Status);
        //  if (data.Status == "OK") {
        //    //alert(data.Value.Title);
        //    //$("#dataDiv").append($("<p>" + data.Value.Title + "</p>"));
        //  }
        //},
        //error: function (e) {
        //  console.log(e);
        //}
      });

    }

    this.login = function (username, password, callback, callbackArgs) {

      var self = this;

      var loginData = {
        userName: username,
        password: password
      };

      var call = this.call('@Url.Action("LogIn", "RemoteSession")', "POST", loginData);
      call.done(function (data, textStatus, jqXHR) {
        self.token(data.Token);

        if (callback) {
          callback(callbackArgs, self);
        }
      });

    };

    this.getLocation = function (args, context, bindToKnockout) {

      var self = context;

      var call = self.call('/api/@Url.Action("GetLocation", "Location")', "GET", { id: args.id }, self.token());
      call.done(function (data, textStatus, jqXHR) {
        if (bindToKnockout == true) {
          self.locations.push(data);
        }
      });

    };

    this.getLocationIdsByLocation = function (args, context) {

      var self = context;

      var call = self.call('/api/@Url.Action("GetLocation", "Location")', "GET", { latitude: 41.175531, longitude: -112.00777, maxDistanceKilometers: 100000, maxLocations: 100 }, self.token());
      call.done(function (data, textStatus, jqXHR) {
        self.locationIds = ko.observableArray(data);

        //self.getLocations(self, true);
        //for (var i = 0; i < self.locationIds().length; i++) {
        //  self.getLocation({ id: self.locationIds()[i], dateLastModified: null }, self);
        //}
      });

    };

    this.getLocations = function (context, bindToKnockout) {

      var self = context;

      self.locations.removeAll();

      if (self.locationIds() && self.locationIds().length > 0) {
        for (var i = 0; i < self.locationIds().length; i++) {
          self.getLocation({ id: self.locationIds()[i], dateLastModified: null }, self, bindToKnockout);
        }
      }

    };

    this.getLocations_click = function (e) {

      var self = this;

      self.getLocations(self, true);

    };

    this.bombard = function () {

      var self = this;

      for (var i = 0; i < 100; i++) {
        self.getLocations(self, false);
      }

    };

    this.getUserOwnedEditedLocations = function (args, context) {

      var self = context;

      var call = self.call('/api/@Url.Action("GetUserOwnedEditedLocations", "Location")', "POST", null, self.token());
      call.done(function (data, textStatus, jqXHR) {
        var t = "t";

        //self.getLocations(self, true);
        //for (var i = 0; i < self.locationIds().length; i++) {
        //  self.getLocation({ id: self.locationIds()[i], dateLastModified: null }, self);
        //}
      });

    };

    this.getLocationImage = function (args, context) {

      var self = context;

      var call = self.call('/api/@Url.Action("GetLocationImage", "Location")/' + 1, "POST", { id: 1 }, self.token());
        call.done(function (data, textStatus, jqXHR) {
          var t = "t";

          //self.getLocations(self, true);
          //for (var i = 0; i < self.locationIds().length; i++) {
          //  self.getLocation({ id: self.locationIds()[i], dateLastModified: null }, self);
          //}
        });

      };

      this.sightsAndSoundsTest = function(args, context) {

        var self = context;

        var call = self.call('/api/@Url.Action("GetPagedVideosByGHLocationId", "SightsAndSounds")', "GET", { id: 1, page: 1, pageSize: 10 }, self.token());
        call.done(function (data, textStatus, jqXHR) {
          var t = "t";

          //self.getLocations(self, true);
          //for (var i = 0; i < self.locationIds().length; i++) {
          //  self.getLocation({ id: self.locationIds()[i], dateLastModified: null }, self);
          //}
        });

      };

      this.constructor();
    }

    $(document).ready(function () {

      try {
        ko.applyBindings(new RestTest());
      }
      catch (ex) {
        alert(ex);
      }

    });

  </script>
}

GhostHuntAR/GhostHuntAR.Web/Views/CacheTest/SoundTests.cshtml
@model GhostHuntAR.Web.Controllers.CacheTestModel

@{
    ViewBag.Title = "Sound Tests";
}

<h2>Sound Tests</h2>

GhostHuntAR/GhostHuntAR.Web/Views/CacheTest/TextTests.cshtml
@{
    ViewBag.Title = "Text Tests";
}

<h2>Text Tests</h2>

GhostHuntAR/GhostHuntAR.Web/Views/CacheTest/VideoTests.cshtml
@{
    ViewBag.Title = "Video Tests";
}

<h2>Video Tests</h2>